config/routes.rb
Survey::Application.routes.draw do

  resources :infos

  resources :diagnostics
  match "/diagnostics/:diagnostic_id/admin" => "diagnostics#admin", :as => 'diagnostic_admin'
  match "/diagnostics/:diagnostic_id/click/:x/:y/:rotation" => "diagnostics#click", :as => 'diagnostic_click'
  match "/diagnostics/:id/segment/:segment_id" => "diagnostics#show", :as => 'diagnostic_segment'
  match "/diagnostics_edit" => "diagnostics#all"
  match "/diagnostics/:diagnostic_id/buy_now" =>"diagnostics#buy_now", :as => 'diagnostic_buy_now'

  match "/transactions/:transaction_hash/paid" =>"transactions#paid", :as => 'transaction_paid'
  match "/transactions/thankyou" =>"transactions#thankyou", :as => 'thank_you'

  match "/diagnostics/:diagnostic_id/:user_id/show_pdf" =>"diagnostics#show_pdf", :as => 'diagnostic_show_pdf'

  resources :segments, :except => :index
  match "/segments/new/:diagnostic_id" => "segments#new", :as => 'new_segment'
  match "/segments/:segment_id/questions" => "segments#questions", :as => 'segment_questions'

  resources :questions, :except => :index
  match "/questions/new/:segment_id" => "questions#new", :as => 'new_question'
  match "/questions/:segment_id" => "questions#show"

  resources :sub_questions, :except => :index
  match "/sub_questions/new/:question_id" => "sub_questions#new", :as => 'new_sub_question'
  match "/sub_questions/select/:sub_question_id" => "sub_questions#select", :as => 'select_sub_question'

  resources :responses, :except => [:index, :show]
  match "/responses/new/:segment_id" => "responses#new", :as => 'new_response'

  resources :users, :only => [:index, :show]
  match '/search' => 'users#index'
  match '/reset_password/:id' => 'users#reset_password', :as => 'reset_password'

  as :user do
    get '/register', to: 'devise/registrations#new', :as => :register
    get '/login', to: 'devise/sessions#new', :as => :login
    get '/logout', to: 'devise/sessions#destroy', :as => :logout
    get '/edit', to: 'devise/registrations#edit', :as => :edit
  end

  devise_for :users, controllers: { confirmations: 'confirmations', :passwords => "passwords" }

  get "home/index"
  root :to => "home#index"

end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base

  include Magick

  attr_accessible :description, :name

  validates :name, presence: true, length: { minimum: 2}

  validates :description, presence: true, length: { minimum: 2}

  has_many :segments, dependent: :destroy

  has_many :transactions

  after_save :make_wheel

  def has_wheel?
    File.exist?("#{Rails.root}public/wheels/wheel_#{self.id}.png")
  end

  def make_chart_for_user(user_id)
    g = Gruff::Spider.new(100,1200)
    g.hide_axes = false
    g.hide_text = false
    g.transparent_background = false
    g.legend_font_size = 10
    g.bottom_margin = 40
    g.font = ("app/assets/fonts/HelveticaNeue.ttf")
    g.theme = {
      :colors => %w(grey),
      :marker_color => 'black',
      :background_colors => %w(#f5f5f5 #f5f5f5)
    }
    if self.segments.count > 3
      g.rotation = 180/self.segments.count
      self.segments.each do |segment|
        g.data word_wrap("#{segment.name} #{segment.score_for_user(user_id).round}%"), segment.score_for_user(user_id)
      end
    end

    g.write("public/results/#{self.id}-#{user_id}.png")
  end

  def make_wheel
    font_size = 12
    inner_radius = 190
    inner_diameter = inner_radius * 2
    border_width = 10
    spoke_width = 70
    hub_size = 40
    hub_margin = 10
    text_pos = 100
    total_diameter = inner_diameter + (2 * border_width)
    centre = total_diameter / 2
    gc = Image.new(total_diameter, total_diameter) { self.background_color = "transparent" }

    # Draw background
    circle = Magick::Draw.new
    circle.fill('#f5f5f5')
    circle.ellipse(centre, centre, (inner_diameter + border_width)  / 2, (inner_diameter + border_width) / 2, 0, 360)
    circle.draw(gc)

    # Draw spokes
    segment_number = 0
    if self.segments.count > 0
      segment_gap = 360 / self.segments.count
    else
      segment_gap = 0
    end
    self.segments.each do |seg|
      line = Magick::Draw.new
      line.stroke('#d5d5d5')
      line.stroke_width(50)
      line.line(centre, centre, centre + (inner_radius + (border_width / 2)) * Math::cos(degrees_to_radians(segment_number * segment_gap)), centre + (inner_radius + (border_width / 2)) * Math::sin(degrees_to_radians(segment_number * segment_gap)))
      line.draw(gc)
      segment_number += 1
    end

    # Draw outline of circle
    circle = Magick::Draw.new
    circle.stroke('#e5e5e5')
    circle.stroke_width(border_width)
    circle.fill_opacity(0)
    circle.ellipse(centre, centre, (inner_diameter + border_width)  / 2, (inner_diameter + border_width) / 2, 0, 360)
    circle.draw(gc)


    # Draw centre hub
    hub = Magick::Draw.new
    hub.fill('#f5f5f5')
    hub.ellipse(centre, centre, hub_size, hub_size, 0, 360)
    hub.draw(gc)


    # Annotate spoke with text
    text_number = 0
    if self.segments.count > 0
      text_gap = 360 / self.segments.count
    else
      text_gap = 0
    end

    self.segments.each do |seg|
      line = 0
      text = word_wrap(seg.name, 20)
      rows = text.split("\n")
      if rows.count == 1
        rows.each do |row|
          scratch_gc = Draw.new
          scratch_gc.pointsize(font_size)
          scratch_gc.font("assets/fonts/HelveticaNeue.ttf")
          metrics = scratch_gc.get_type_metrics(row)
          width = metrics.width
          height = (metrics.bounds.y2 - metrics.bounds.y1).round
          indent = (inner_radius - hub_size - hub_margin - width ) / 2
          x = centre + (hub_margin + hub_size + indent) * Math::cos(degrees_to_radians(text_number * text_gap))
          y = centre + (hub_margin + hub_size + indent) * Math::sin(degrees_to_radians(text_number * text_gap))
          Draw.new.annotate(gc, 0, 0,x, y, "#{row}") {
            self.pointsize = font_size
            self.font("assets/fonts/HelveticaNeue.ttf")
            self.rotation = text_gap * text_number
            line += 1
          }
        end
        text_number += 1
      else
        rows.each do |row|
          scratch_gc = Draw.new
          scratch_gc.pointsize(font_size)
          scratch_gc.font("assets/fonts/HelveticaNeue.ttf")
          metrics = scratch_gc.get_type_metrics(row)
          width = metrics.width
          height = (metrics.bounds.y2 - metrics.bounds.y1).round
          indent = (inner_radius - hub_size - hub_margin - width ) / 2
          x = centre + (hub_margin + hub_size + indent) * Math::cos(degrees_to_radians(text_number * text_gap))
          y = centre + (hub_margin + hub_size + indent) * Math::sin(degrees_to_radians(text_number * text_gap))
          case text_gap * text_number
            when 0
              angle = 90 - (text_gap * text_number)
              x += a_adjust(angle, line, height, true)
              y += b_adjust(angle, line, height, true)
            when 90
              angle = 90 - (text_gap * text_number)
              x += a_adjust(angle, line, height, false)
              y += b_adjust(angle, line, height, false)
            when 0..90
              angle = 90 - (text_gap * text_number)
              x += a_adjust(angle, line, height, false)
              y += b_adjust(angle, line, height, true)
            when 180
              angle = 90 - (text_gap * text_number)
               x += a_adjust(angle, line, height, true)
               y += b_adjust(angle, line, height, true)
            when 90..180
              angle = 90 - (270 - text_gap * text_number)
              x += b_adjust(angle, line, height, true)
              y += a_adjust(angle, line, height, false)
            when 270
              angle = 90 - (text_gap * text_number)
              x += a_adjust(angle, line, height, false)
              y += b_adjust(angle, line, height, false)
            when 180..270
              angle = 90 - (text_gap * text_number - 270)
              x += b_adjust(angle, line, height, true)
              y += a_adjust(angle, line, height, true)
            when 270..360
              angle = 90 - (360 - text_gap * text_number)
              x += a_adjust(angle, line, height, true)
              y += b_adjust(angle, line, height, true)
            end
            line += 1
            Draw.new.annotate(gc, 0, 0, x, y, "#{row}") {
              self.pointsize = font_size
              self.font("assets/fonts/HelveticaNeue.ttf")
              self.rotation = text_gap * text_number
            }
          end
        text_number += 1
      end
    end


    gc.write("public/wheels/wheel_#{self.id}.png")

  end

  def segment_from_x_y_rotation(x,y,rotation)
    x_from_centre = x.to_f - 200
    y_from_centre = 200 - y.to_f

    if x_from_centre >= 0 && y_from_centre >= 0
      angle = 90 - radians_to_degrees(Math::atan(y_from_centre / x_from_centre)) - rotation.to_f
    elsif x_from_centre >= 0 && y_from_centre < 0
      angle = 90 - radians_to_degrees(Math::atan(y_from_centre / x_from_centre)) - rotation.to_f
    elsif x_from_centre < 0 && y_from_centre < 0
      angle = 270 - radians_to_degrees(Math::atan(y_from_centre / x_from_centre)) - rotation.to_f
    elsif x_from_centre < 0 && y_from_centre >= 0
      angle = 270 - radians_to_degrees(Math::atan(y_from_centre / x_from_centre)) - rotation.to_f
    else
      angle = 0
    end


    if self.segments.count > 0
      segment_gap = 360 / self.segments.count
    else
      segment_gap = 360
    end
    segment_number =  ((angle - (segment_gap / 2)) / segment_gap).floor

    self.segments[segment_number - 1]
  end

  def complete_for_user(user)
    if self.segments.count > 0
      self.segments.map{|x| x.complete_for_user(user)}.sum / self.segments.count
    else
      0
    end
  end

  def user_response(user_id)
    self.segments.map{|x| x.user_response(user_id).try(:description)}.select{|x| x.present?}.join(' ')
  end

  private

  def degrees_to_radians(deg)
    deg * Math::PI / 180
  end

  def radians_to_degrees(rad)
    rad * 180 / Math::PI
  end

  def word_wrap(text, columns = 20)
    text.split("\n").collect do |line|
      line.length > columns ? line.gsub(/(.{1,#{columns}})(\s+|$)/, "\\1\n").strip : line
    end * "\n"
  end

  def a_adjust(angle, line, height, positive)
    if positive
      if line == 0
        0 - ((height / 2) * Math::cos(degrees_to_radians(angle)))
      elsif line == 1
        height * Math::cos(degrees_to_radians(angle))
      end
    else
      if line == 0
        (height / 2) * Math::cos(degrees_to_radians(angle))
      elsif line == 1
        0 - (height * Math::cos(degrees_to_radians(angle)))
      end
    end
  end

  def b_adjust(angle, line, height, positive)
    if positive
      if line == 0
        0 - ((height / 2) * Math::sin(degrees_to_radians(angle)))
      elsif line == 1
        height * Math::sin(degrees_to_radians(angle))
      end
    else
      if line == 0
        (height / 2) * Math::sin(degrees_to_radians(angle))
      elsif line == 1
        0 - (height * Math::sin(degrees_to_radians(angle)))
      end
    end
  end
end

app/controllers/diagnostics_controller.rb
class DiagnosticsController < ApplicationController
  # GET /diagnostics
  # GET /diagnostics.json
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :can_edit, only: [:new, :create, :edit, :update, :destroy, :all]
  before_filter :check_paid , only: [:show_pdf]

  def admin
     @diagnostic = Diagnostic.find(params[:diagnostic_id])
  end

  def all
    @diagnostics = Diagnostic.all
    @infos = Info.order("id ASC")
  end

  def chart
    @diagnostics = Diagnostic.all
  end

  def index
    @diagnostics = Diagnostic.all
    @diagnostics.each do |diagnostic|
      diagnostic.make_chart_for_user(current_user.id) if user_signed_in?
    end
  end

  # GET /diagnostics/1
  def show
    @diagnostic = Diagnostic.find(params[:id])
    @segment = Segment.find(params[:segment_id]) if params[:segment_id]
    @diagnostic.make_wheel() if !@diagnostic.has_wheel?
    @crud_state = "show"
  end

  # GET /diagnostics/new
  def new
    @diagnostic = Diagnostic.new
    @crud_state = "new"
  end

  # GET /diagnostics/1/edit
  def edit
    @diagnostic = Diagnostic.find(params[:id])
    @crud_state = "edit"
  end

  # POST /diagnostics
  def create
    @diagnostic = Diagnostic.new(params[:diagnostic])
    @crud_state = "create"

    if @diagnostic.save
      redirect_to @diagnostic, notice: 'Diagnostic was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /diagnostics/1
  def update
    @diagnostic = Diagnostic.find(params[:id])
    @crud_state = "update"
    @diagnostic.make_wheel()

    if @diagnostic.update_attributes(params[:diagnostic])
      @diagnostic.make_wheel()
      redirect_to diagnostics_url, notice: 'Diagnostic was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /diagnostics/1
  def destroy
    @diagnostic = Diagnostic.find(params[:id])
    if @diagnostic.destroy
      redirect_to diagnostics_url, notice: 'Diagnostic was successfully deleted.'
    else
      redirect_to diagnostics_url, alert: 'Diagnostic was not deleted.'
    end
  end

  def click
    @diagnostic = Diagnostic.find(params[:diagnostic_id])
    @diagnostic.make_wheel() if !@diagnostic.has_wheel?
    @segment = @diagnostic.segment_from_x_y_rotation(params[:x],params[:y],params[:rotation])
    render action: "show"
  end

  def buy_now
    @diagnostic = Diagnostic.find(params[:diagnostic_id])
    begin
      @transaction = Transaction.create!(:user_id => current_user.id, :diagnostic_id => @diagnostic.id)
    rescue
      @transaction = current_user.transactions.where(:diagnostic_id => @diagnostic.id).first
    end
  end

  def show_pdf
    @diagnostic = Diagnostic.find(params[:diagnostic_id])
    @user = User.find(params[:user_id])
    @introduction = Info.where(:name => "introduction").first.content
    @help = Info.where(:name =>  "how we can help you").first.content
    @organisation = Info.where(:name =>  "organisation").first.content
    @email = Info.where(:name =>  "email").first.content
    @phone = Info.where(:name =>  "phone").first.content
    respond_to do |format|
      format.pdf do
        render pdf: "file_name"   # Excluding ".pdf" extension.
      end
    end
  end

  private
  def can_edit
	  if !(user_signed_in? && current_user.is_admin?)
  	  redirect_to :root, alert: "You must be admin to do that"
    end
	end

  def check_paid
    @user = User.find(params[:user_id])
    if @user.transactions.where(:completed => true).where(:diagnostic_id => params[:diagnostic_id]).empty? && !@user.admin?
      redirect_to :root, alert: "You have not paid for that"
    end
  end
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/views/diagnostics/_chart.html.haml
- @diagnostics.each do |diagnostic|
  .row.span12.well.section.chart
    .row
      .span7
        %h3.no-top-margin
          =link_to (diagnostic.name+" Results").capitalize, diagnostic_path(diagnostic.id)
      .span5.admin.pull-right.margin-top
        - if check_admin(current_user)
          = link_to 'Edit Content', diagnostic_admin_path(diagnostic), id: 'show-content', data: { diagnostic_id: diagnostic.id }
          |
          \#{link_to 'Edit Name and Description', edit_diagnostic_path(diagnostic)}
          |
          \#{link_to "Delete", "#delete#{diagnostic.id}",  :'data-toggle' => "modal"}
    .row.head2
      = diagnostic.description
    .row.head2.mt-2  
      -if user_signed_in?
        -if current_user.transactions.where(:completed => true).where(:diagnostic_id => diagnostic.id).present?
          =# Commented out as the report will be sent manually
          =# link_to "Download your personalised diagnostic report", diagnostic_show_pdf_path(diagnostic.id, current_user) + ".pdf", class: "btn btn-primary"
          Thank you for purchasing your personalised report. It will be emailed to you once your results have been reviewed.
        -else
          = link_to "Buy your personalised diagnostic report", diagnostic_buy_now_path(diagnostic.id), class: "btn btn-primary"
    - if user_signed_in?
      %img{src: "/results/#{diagnostic.id}-#{current_user.id}.png"}/

      .progress.progress-striped
        .bar{style: "width:#{diagnostic.complete_for_user(current_user)}%"}
          .black
            = "#{diagnostic.complete_for_user(current_user)}% Complete"
  .modal.fade{id: "delete#{diagnostic.id}"}
    .modal-header
      %a.close{"data-dismiss" => "modal"} x
      %h3 Are you sure you want to delete this diagnostic?
    .modal-body
      %p If you do all its content will be lost
    .modal-footer
      %a.btn{"data-dismiss" => "modal", href: "#"} Close
      = link_to 'Delete', diagnostic, method: :delete, class: 'btn btn-primary'

app/views/diagnostics/_form.html.haml
- if @diagnostic.errors.any?
  .alert.alert-danger
    %button.close{"data-dismiss" => "alert"} x
    %h3
      = pluralize(@diagnostic.errors.count, "error")
      prevented this diagnostic from being saved:
    %ul
      - @diagnostic.errors.full_messages.each do |msg|
        %li= msg
%h2
  = crud_state_to_name(@crud_state)
  diagnostic
= simple_form_for(@diagnostic, :html => { class: "well" }) do |f|
  .form-inputs
    = f.input :name
    = f.input :description, :input_html => {:rows => 5}
  .form-actions
    = f.submit "Save", class: "btn"

app/views/diagnostics/admin.html.haml
.container
  - flash.each do |type, message|
    %div{class: "alert alert-block #{flash_class(type)}"}
      %button.close{"data-dismiss" => "alert"} x
      %h4= flash_header message
      %div= message

  %h1= @diagnostic.name

  .row
    .span12
      - if check_admin(current_user)
        = link_to 'New Segment', new_segment_path(@diagnostic), class: 'btn btn-top'


  -@diagnostic.segments.each do |segment|
    .span12
      .row.well.info.section
        .span8
          =segment.name
        .span3.admin
          - if check_admin(current_user)
            = link_to 'Edit', edit_segment_path(segment)
            |
            = link_to "Delete", "#delete_segment#{segment.id}",  :'data-toggle' => "modal"

        .row.span12
          - if check_admin(current_user)
            = link_to 'New Question', new_question_path(segment)
            %br
            = link_to 'New Response', new_response_path(segment)

      - segment.responses.sort_by { |k, v| k[:value] }.each do |response|
        .row.well.section.response
          .span4
            ="#{response.value}%"
          .span4
            = response.description
          .span3.admin
            - if check_admin(current_user)
              = link_to 'Edit', edit_response_path(response)
              |
              = link_to "Delete", "#delete_response#{response.id}",  :'data-toggle' => "modal"

      - segment.questions.each do |question|
        .row.well.section
          .span4
            = question.name
          .span4
            = question.description
          .span3.admin
            - if check_admin(current_user)
              = link_to 'Edit', edit_question_path(question)
              |
              = link_to "Delete", "#delete_question#{question.id}",  :'data-toggle' => "modal"
          .row.span12
            - if check_admin(current_user)
              = link_to 'New Sub question', new_sub_question_path(question)

        - question.sub_questions.sort_by { |k, v| k[:value] }.reverse.each do |sub_question|
          .row.well.section
            .span1
            .span3
              = sub_question.name
            .span3
              = sub_question.evidence
            .span1
              = "#{sub_question.value}%"
            .span3.admin
              - if check_admin(current_user)
                = link_to 'Edit', edit_sub_question_path(sub_question)
                |
                = link_to "Delete", "#delete_sub_question#{sub_question.id}",  :'data-toggle' => "modal"


-@diagnostic.segments.each do |segment|
  .modal.fade{id: "delete_segment#{segment.id}"}
    .modal-header
      %a.close{"data-dismiss" => "modal"} x
      %h3 Are you sure you want to delete this segment?
    .modal-body
      %p If you do all its content will be lost
    .modal-footer
      %a.btn{"data-dismiss" => "modal", href: "#"} Close
      = link_to 'Delete', segment, method: :delete, class: 'btn btn-primary'

  -segment.questions.each do |question|
    .modal.fade{id: "delete_question#{question.id}"}
      .modal-header
        %a.close{"data-dismiss" => "modal"} x
        %h3 Are you sure you want to delete this question?
      .modal-body
        %p If you do all its content will be lost
      .modal-footer
        %a.btn{"data-dismiss" => "modal", href: "#"} Close
        = link_to 'Delete', question, method: :delete, class: 'btn btn-primary'

    -question.sub_questions.each do |sub_question|
      .modal.fade{id: "delete_sub_question#{sub_question.id}"}
        .modal-header
          %a.close{"data-dismiss" => "modal"} x
          %h3 Are you sure you want to delete this sub question?
        .modal-body
          %p If you do all its content will be lost
        .modal-footer
          %a.btn{"data-dismiss" => "modal", href: "#"} Close
          = link_to 'Delete', sub_question, method: :delete, class: 'btn btn-primary'

  -segment.responses.each do |response|
    .modal.fade{id: "delete_response#{response.id}"}
      .modal-header
        %a.close{"data-dismiss" => "modal"} x
        %h3 Are you sure you want to delete this response?
      .modal-body
        %p If you do all its content will be lost
      .modal-footer
        %a.btn{"data-dismiss" => "modal", href: "#"} Close
        = link_to 'Delete', response, method: :delete, class: 'btn btn-primary'

app/views/diagnostics/all.html.haml
%h1.head Listing diagnostics
.row.span12
  = link_to 'New Diagnostic', new_diagnostic_path, class: 'btn btn-top'

- @diagnostics.each do |diagnostic|
  .row.span12.well.section.chart
    = link_to diagnostic.name, diagnostic_path(diagnostic)
    %span.admin.pull-right
      - if check_admin(current_user)
        = link_to 'Edit Content', diagnostic_admin_path(diagnostic), id: 'show-content', data: { diagnostic_id: diagnostic.id }
        |
        \#{link_to 'Edit Name and Description', edit_diagnostic_path(diagnostic)}
        |
        \#{link_to "Delete", "#delete#{diagnostic.id}",  :'data-toggle' => "modal"}


  .modal.fade{id: "delete#{diagnostic.id}"}
    .modal-header
      %a.close{"data-dismiss" => "modal"} x
      %h3 Are you sure you want to delete this diagnostic?
    .modal-body
      %p If you do all its content will be lost
    .modal-footer
      %a.btn{"data-dismiss" => "modal", href: "#"} Close
      = link_to 'Delete', diagnostic, method: :delete, class: 'btn btn-primary'


.span12
  -@infos.each do |info|
    =render 'infos/form', :@info => info

app/views/diagnostics/buy_now.html.haml
%h2
  Buy peronalised report

.well
  Clicking on the button below will take you to Paypal where you can pay for a personalised report of how you can improve at all segments of the wheel. Your report will be emailed to you once your results have been reviewed.

  %p.mt-1

    %script{:async => "async", "data-amount" => "10", "data-button" => "buynow", "data-return" => "#{@host}/transactions/thankyou?auth_token=#{current_user.authentication_token}", "data-callback" => "#{@host}/transactions/#{@transaction.security_hash}/paid", "data-currency" => "GBP", "data-name" => "Diagnostic Results", "data-shipping" => "0", "data-tax" => "0", :src => "https://www.paypalobjects.com/js/external/paypal-button.min.js?merchant=info@archimedes-training.co.uk"}

  %script
    $(window).bind("load", function() {
    $('#paypal-button').remove();
    $('.paypal-button:last').removeClass("paypal-button").removeClass("large").addClass("btn paypal")
    });

%p.mt-1
  If you have any questions please email
  =link_to "info@archimedes-training.co.uk", "mailto: info@archimedes-training.co.uk"

app/views/diagnostics/click.html.haml
DELETE ME

app/views/diagnostics/click.js.erb
$("#questions").html('<%= escape_javascript(render('segments/questions', :segment => @segment))%>');
$("#wheel").rotate({animateTo:<%= @segment.segment_roation %>});

app/views/diagnostics/index.html.haml
.row.span12.pad1
  - if check_admin(current_user)
    = link_to 'New Diagnostic', new_diagnostic_path, class: 'btn btn-top'

=render "chart", :@diagnostics => @diagnostics

app/views/diagnostics/show.html.haml
%p
  %h2.head
    =@diagnostic.name
%p
  %h5.head
    =@diagnostic.description

.span12.large.pad1
  -if user_signed_in? && @diagnostic.complete_for_user(current_user) > 0
    .progress.progress-striped
      .bar{:style => "width:"+"#{@diagnostic.complete_for_user(current_user)}%"}
        .black
          ="#{@diagnostic.complete_for_user(current_user)}% Complete"

.span6
  = link_to(diagnostic_click_path(@diagnostic.id, 0, 0, 0), :remote => true, :id => 'wheel-link') do
    #wheelcontainer
      #wheel
        %img{:src => "/wheels/wheel_#{@diagnostic.id}.png"}

.fillright
  #questions
    -if @segment
      =render 'segments/questions', :@segment => @segment
    -else
      .alert.small
        %h3
          What Next?
        %h4
        Click on the spokes to navigate around the various questions

.span12
  =link_to "Back to all diagnostics", diagnostics_path

:javascript
  $("#wheelcontainer").on("click", function(e) {
    if (!window.spinning) {
      window.spinning = true;
      var offset = $(this).offset();
      var x = Math.floor(e.clientX - offset.left);
      var y = Math.floor(e.clientY - offset.top);
      $('#wheel-link').attr("href", "/diagnostics/#{@diagnostic.id}/click/" + x + "/" + y + "/" + getRotationDegrees($("#wheel")));
    };
  });


  if (history && history.pushState) {
    $(function() {
      $("#wheelcontainer").on("click", function(e) {
        $.getScript(this.href);
        var offset = $(this).offset();
        var x = Math.floor(e.clientX - offset.left);
        var y = Math.floor(e.clientY - offset.top);
        history.replaceState(null, document.title, "/diagnostics/#{@diagnostic.id}/click/" + x + "/" + y + "/" + getRotationDegrees($("#wheel")) + ".html");
        e.preventDefault();
      });
      $.getScript(location.href);
      $("#wheel").transition({ rotate: '#{@segment.segment_roation if @segment}deg' });
    });
  }


  function getRotationDegrees(obj) {
      var matrix = obj.css("-webkit-transform") ||
      obj.css("-moz-transform")    ||
      obj.css("-ms-transform")     ||
      obj.css("-o-transform")      ||
      obj.css("transform");
      if(matrix !== 'none') {
          var values = matrix.split('(')[1].split(')')[0].split(',');
          var a = values[0];
          var b = values[1];
          var angle = Math.round(Math.atan2(b, a) * (180/Math.PI));
      } else { var angle = 0; }
      return (angle < 0) ? angle +=360 : angle;
  }

app/views/diagnostics/show.js.erb
<% if @segment %>
	$("#questions").html('<%= escape_javascript(render 'segments/questions', :@segment => @segment)%>');
	$("#wheel").transition({ rotate: '<%= @segment.segment_roation %>deg' });
	window.spinning = false;
<% end %>

app/views/diagnostics/show_pdf.pdf.haml
:css
  body{
    font-size: 20pt;
    padding: 0;
    margin: 0;
  }


  h1{
    font-size: 44pt;
  }

  h2 {
    font-size: 38pt;
  }


  h2 {
    font-size: 28pt;
    margin: 9px 0px 5px 0px;
  }

  h3 {
    font-size: 20pt;
  }

  h4 {
    font-size: 20pt;
    padding-bottom: 50pt;
  }

  h5 {
    font-size: 20pt;
  }

  .center {
    text-align: center;
    position: absolute;
    margin-left: 200px;
    left: 0;
    right: 0;
  }

  .content {
    padding-top:1700px;
    width: 200%;
  }
.center
  %h1 Archimedes Earth
  %h3=@organisation

  %h1 Framework of Excellence

  %h4 Quality Mark Award

  %h5 Diagnostic Report

  %h5 For

  %h5=@user.full_name
  %h5="(#{@user.organisation})"

.content
  %h5 Introduction
  %p=@introduction

  %h5 Results
  %p="#{@diagnostic.user_response(@user.id)} Here is the radar graph for your the diagnostic:"
  = image_tag "#{Rails.root}/public/results/#{@diagnostic.id}-#{@user.id}.png"

  %h5 How We Can Help You
  %p=@help

  %h5 Contact Us
  %p=@organisation
  %p=@email
  %p=@phone