config/routes.rb
Survey::Application.routes.draw do

  resources :infos

  resources :diagnostics
  match "/diagnostics/:diagnostic_id/admin" => "diagnostics#admin", :as => 'diagnostic_admin'
  match "/diagnostics/:diagnostic_id/click/:x/:y/:rotation" => "diagnostics#click", :as => 'diagnostic_click'
  match "/diagnostics/:id/segment/:segment_id" => "diagnostics#show", :as => 'diagnostic_segment'
  match "/diagnostics_edit" => "diagnostics#all"
  match "/diagnostics/:diagnostic_id/buy_now" =>"diagnostics#buy_now", :as => 'diagnostic_buy_now'

  match "/transactions/:transaction_hash/paid" =>"transactions#paid", :as => 'transaction_paid'
  match "/transactions/thankyou" =>"transactions#thankyou", :as => 'thank_you'

  match "/diagnostics/:diagnostic_id/:user_id/show_pdf" =>"diagnostics#show_pdf", :as => 'diagnostic_show_pdf'

  resources :segments, :except => :index
  match "/segments/new/:diagnostic_id" => "segments#new", :as => 'new_segment'
  match "/segments/:segment_id/questions" => "segments#questions", :as => 'segment_questions'

  resources :questions, :except => :index
  match "/questions/new/:segment_id" => "questions#new", :as => 'new_question'
  match "/questions/:segment_id" => "questions#show"

  resources :sub_questions, :except => :index
  match "/sub_questions/new/:question_id" => "sub_questions#new", :as => 'new_sub_question'
  match "/sub_questions/select/:sub_question_id" => "sub_questions#select", :as => 'select_sub_question'

  resources :responses, :except => [:index, :show]
  match "/responses/new/:segment_id" => "responses#new", :as => 'new_response'

  resources :users, :only => [:index, :show]
  match '/search' => 'users#index'
  match '/reset_password/:id' => 'users#reset_password', :as => 'reset_password'

  as :user do
    get '/register', to: 'devise/registrations#new', :as => :register
    get '/login', to: 'devise/sessions#new', :as => :login
    get '/logout', to: 'devise/sessions#destroy', :as => :logout
    get '/edit', to: 'devise/registrations#edit', :as => :edit
  end

  devise_for :users, controllers: { confirmations: 'confirmations', :passwords => "passwords" }

  get "home/index"
  root :to => "home#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :name, :description, :segment_id

  belongs_to :segment

  validates :name, presence: true, length: { minimum: 2}

  validates :segment_id, presence: true

  has_many :sub_questions, dependent: :destroy

  has_many :views

  def complete_for_user(user)
    (self.views.where(:user_id => user.id).present? ? 100 : 0)
  end

  def position
    pos = 0
    loop_pos = 0
    self.segment.questions.each do |que|
      if que.id == self.id
        pos = loop_pos
      end
      loop_pos += 1
    end
    pos
  end

  def next_segment
    if self.segment.last_segment?
      self.segment.diagnostic.segments.first
    else
      self.segment.diagnostic.segments[self.segment.number + 1]
    end
  end

  def previous_segment
    if self.segment.number == 0
      self.segment.diagnostic.segments.last
    else
      self.segment.diagnostic.segments[self.segment.number - 1]
    end
  end

  def last_question?
    self.position == self.segment.questions.count - 1
  end

  def next_question
    if self.last_question?
      self.next_segment.questions.first
    else
      self.segment.questions[self.position + 1]
    end
  end

  def previous_question
    if self.position == 0
      self.previous_segment.last_question
    else
      self.segment.questions[self.position - 1]
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :can_edit, only: [:new, :create, :edit, :update, :destroy]
  before_filter :can_take, only: [:show]

  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
    @question = Question.find(params[:id]) || SubQuestion.find(params[:sub_question_id]).question
    @segment = @question.segment
    @crud_state = "show"
    begin
      View.create!(:user_id => current_user.id, :question_id => @question.id)
    rescue
      #do nothing
    end
  end

  # GET /questions/new
  def new
    @question = Question.new(:segment_id => params[:segment_id])
    @crud_state = "new"
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
    @crud_state = "edit"
  end

  # POST /questions
  def create
    @question = Question.new(params[:question])
    @crud_state = "create"

    if @question.save
      redirect_to diagnostic_admin_path(@question.segment.diagnostic.id), notice: 'Question was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /questions/1
  def update
    @question = Question.find(params[:id])
    @crud_state = "update"

    if @question.update_attributes(params[:question])
      redirect_to diagnostic_admin_path(@question.segment.diagnostic.id), notice: 'Question was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /questions/1
  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      redirect_to diagnostic_admin_path(@question.segment.diagnostic.id), notice: 'Question was successfully deleted.'
    else
      redirect_to diagnostic_admin_path(@question.segment.diagnostic.id), alert: 'Question was not deleted.'
    end
  end

  private
  def can_edit
	  if user_signed_in?
	    if !current_user.is_admin?
  	    redirect_to :back, alert: "You must be admin to do that"
  	  end
    end
	end


	def can_take
	  if !user_signed_in?
	    redirect_to register_path
	    flash[:message] = "You need to be registered to build your own diagnostic results. It won't take long and is free!"
	  end
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
- if @question.errors.any?
  .alert.alert-danger
    %button.close{"data-dismiss" => "alert"} x
    %h3
      = pluralize(@question.errors.count, "error")
      prevented this question from being saved:
    %ul
      - @question.errors.full_messages.each do |msg|
        %li= msg
%h2
  = crud_state_to_name(@crud_state)
  question
%h4
  = crud_state_to_name(@crud_state)
  question for #{@question.segment.name}
= simple_form_for(@question, :html => { class: "well" }) do |f|
  .form-inputs
    = f.input :name, :input_html => {:rows => 5}
    = f.input :description, :input_html => {:rows => 5}
    %input{name: "question[segment_id]", type: "hidden", value: @question.segment.id}/
  .form-actions
    = f.submit "Save", class: "btn"

app/views/questions/edit.html.haml
= render 'form'

app/views/questions/show.html.haml
.span10
  %p
    %h1.pt-2
      =@segment.name
    %h4
      =@question.name

  %table.table
    %thead
      %th

    %tbody
      - @question.sub_questions.sort_by { |k, v| k[:value] }.each do |subquestion|
        %tr.section{:id => "#{subquestion.id}", :'data-animation' => :true, :'data-html' => :true, :'data-title' => "Evidence", :'data-content' => "#{subquestion.evidence}"}
          %td
            = subquestion.name
          %td
            =link_to "#{subquestion.yes?(current_user) ? '<i class="fa fa-check"></i>' : '&nbsp;'}".html_safe,  select_sub_question_path(subquestion.id), class: "btn select #{subquestion.yes?(current_user) ? 'btn-success' : ''}", id: "select-sub-question-#{subquestion.id}", :remote => true


  -if !@question.next_question.nil? && !@question.previous_question.nil? || true
    .span2
      =link_to 'Previous question', question_path(@question.previous_question), :class => "btn btn-primary pull-left"

  -if !@question.next_question.nil? && !@question.previous_question.nil? || true
    .span2.offset5
      =link_to 'Next question', question_path(@question.next_question), :class => "btn btn-primary pull-right"


  .gap
    = link_to "Back to Diagnostic", diagnostic_segment_path(@question.segment.diagnostic.id, @question.segment.id)

  - @question.sub_questions.each do |subquestion|
    -if subquestion.evidence.present?
      :javascript
        $(function ()
        {
          $("##{subquestion.id}").popover(
          {
             trigger: 'hover',
             html: true,
             placement: 'right',
          });
        });