config/routes.rb
Survey::Application.routes.draw do

  resources :infos

  resources :diagnostics
  match "/diagnostics/:diagnostic_id/admin" => "diagnostics#admin", :as => 'diagnostic_admin'
  match "/diagnostics/:diagnostic_id/click/:x/:y/:rotation" => "diagnostics#click", :as => 'diagnostic_click'
  match "/diagnostics/:id/segment/:segment_id" => "diagnostics#show", :as => 'diagnostic_segment'
  match "/diagnostics_edit" => "diagnostics#all"
  match "/diagnostics/:diagnostic_id/buy_now" =>"diagnostics#buy_now", :as => 'diagnostic_buy_now'

  match "/transactions/:transaction_hash/paid" =>"transactions#paid", :as => 'transaction_paid'
  match "/transactions/thankyou" =>"transactions#thankyou", :as => 'thank_you'

  match "/diagnostics/:diagnostic_id/:user_id/show_pdf" =>"diagnostics#show_pdf", :as => 'diagnostic_show_pdf'

  resources :segments, :except => :index
  match "/segments/new/:diagnostic_id" => "segments#new", :as => 'new_segment'
  match "/segments/:segment_id/questions" => "segments#questions", :as => 'segment_questions'

  resources :questions, :except => :index
  match "/questions/new/:segment_id" => "questions#new", :as => 'new_question'
  match "/questions/:segment_id" => "questions#show"

  resources :sub_questions, :except => :index
  match "/sub_questions/new/:question_id" => "sub_questions#new", :as => 'new_sub_question'
  match "/sub_questions/select/:sub_question_id" => "sub_questions#select", :as => 'select_sub_question'

  resources :responses, :except => [:index, :show]
  match "/responses/new/:segment_id" => "responses#new", :as => 'new_response'

  resources :users, :only => [:index, :show]
  match '/search' => 'users#index'
  match '/reset_password/:id' => 'users#reset_password', :as => 'reset_password'

  as :user do
    get '/register', to: 'devise/registrations#new', :as => :register
    get '/login', to: 'devise/sessions#new', :as => :login
    get '/logout', to: 'devise/sessions#destroy', :as => :logout
    get '/edit', to: 'devise/registrations#edit', :as => :edit
  end

  devise_for :users, controllers: { confirmations: 'confirmations', :passwords => "passwords" }

  get "home/index"
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable

  before_save :ensure_authentication_token

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :organisation, :authentication_token

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :organisation, presence: true

  has_many :answers

  has_many :transactions

  has_many :views

  def full_name
    "#{first_name} #{last_name}"
  end

  def is_admin?
    admin?
  end

  def self.search(words)
    users = Set.new
    if !words.empty?
      words.split(" ").each do |word|
        users = User.select {|user|
          user.first_name == word.capitalize ||
          user.last_name == word.capitalize ||
          user.organisation == word.capitalize
        }
      end
    end
    if users.nil?
      users = User.all
    end
    users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :can_view

  def index
    if params[:'/search'].try(:[],:words)
      @users = User.search(params[:'/search'][:words])
    else
    @users = User.all
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def reset_password
    @user = User.find(params[:id])
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    password = (0...50).map { o[rand(o.length)] }.join[0..10]
    if @user.update_attributes(:password => password, :password_confirmation => password)
      redirect_to user_path(@user), notice: "The user's new password is #{password}."
    else
      redirect_to user_path(@user), alert: "The user's password could not be reset."
    end
  end



  private
  def can_view
    if user_signed_in? && !current_user.is_admin?
	    redirect_to home_index_path(), alert: "You must be admin to do that!"
	  end
	end
end

app/views/users/index.html.haml
.span12.well.row.top
  %h3
    Search for users
  = semantic_form_for search_path, :method => 'get' do |f|
    %p
      = f.input :words, :class => "search-input mb-2", :placeholder => "Name"

      .span6
        = f.action :submit, :label => "Update search", :"data-loading-text" => "Searching...", :button_html => { :class => 'btn btn-primary btn-block negative-margin-left'}

-@users.each do |user|
  .span12.well.user-info
    %h4= link_to("#{user.full_name} - #{user.organisation}", user_path(user.id))
    -Diagnostic.all.each do |dia|
      .row
        -if tx=user.transactions.where(:completed => true).where(:diagnostic_id => dia.id).first
          .row.span12
            ="Paid for a customised report on #{tx.updated_at.strftime("%e %B %Y")}"
        -if FileTest.exists?("#{Rails.root}/public/results/#{dia.id}-#{user.id}.png")
          .span3
            =image_tag "/results/#{dia.id}-#{user.id}.png"

app/views/users/show.html.haml
.row.span12.pad1
  %h3
    ="#{@user.full_name} - #{@user.organisation}"
    =link_to("Reset password", reset_password_path(@user.id), :class => "btn")
  .negative-margin-top
    =link_to @user.email, "mailto:#{@user.email}"

.row.span12.pad1
  %h5
    ="#{@user.full_name}'s results:"
    

-results = false

-Diagnostic.all.each do |dia|
  
  .row.span12.mb-1
    -if tx=@user.transactions.where(:completed => true).where(:diagnostic_id => dia.id).first
      ="Paid for a customised report on #{tx.updated_at.strftime("%e %B %Y")}"

  -if FileTest.exists?("#{Rails.root}/public/results/#{dia.id}-#{@user.id}.png")
    -results = true
    .row.span12.well.section.chart
      .row
        .span12
          %h3.no-top-margin
            =dia.name
      .row.head2
        = dia.description
        = link_to "Download their personalised diagnostic report", diagnostic_show_pdf_path(dia.id, @user.id) + ".pdf"
        %img{src: "/results/#{dia.id}-#{@user.id}.png"}/

  -if !results
    .row.span12.pad1
      This user has no results