config/routes.rb
Survey::Application.routes.draw do

  resources :infos

  resources :diagnostics
  match "/diagnostics/:diagnostic_id/admin" => "diagnostics#admin", :as => 'diagnostic_admin'
  match "/diagnostics/:diagnostic_id/click/:x/:y/:rotation" => "diagnostics#click", :as => 'diagnostic_click'
  match "/diagnostics/:id/segment/:segment_id" => "diagnostics#show", :as => 'diagnostic_segment'
  match "/diagnostics_edit" => "diagnostics#all"
  match "/diagnostics/:diagnostic_id/buy_now" =>"diagnostics#buy_now", :as => 'diagnostic_buy_now'

  match "/transactions/:transaction_hash/paid" =>"transactions#paid", :as => 'transaction_paid'
  match "/transactions/thankyou" =>"transactions#thankyou", :as => 'thank_you'

  match "/diagnostics/:diagnostic_id/:user_id/show_pdf" =>"diagnostics#show_pdf", :as => 'diagnostic_show_pdf'

  resources :segments, :except => :index
  match "/segments/new/:diagnostic_id" => "segments#new", :as => 'new_segment'
  match "/segments/:segment_id/questions" => "segments#questions", :as => 'segment_questions'

  resources :questions, :except => :index
  match "/questions/new/:segment_id" => "questions#new", :as => 'new_question'
  match "/questions/:segment_id" => "questions#show"

  resources :sub_questions, :except => :index
  match "/sub_questions/new/:question_id" => "sub_questions#new", :as => 'new_sub_question'
  match "/sub_questions/select/:sub_question_id" => "sub_questions#select", :as => 'select_sub_question'

  resources :responses, :except => [:index, :show]
  match "/responses/new/:segment_id" => "responses#new", :as => 'new_response'

  resources :users, :only => [:index, :show]
  match '/search' => 'users#index'
  match '/reset_password/:id' => 'users#reset_password', :as => 'reset_password'

  as :user do
    get '/register', to: 'devise/registrations#new', :as => :register
    get '/login', to: 'devise/sessions#new', :as => :login
    get '/logout', to: 'devise/sessions#destroy', :as => :logout
    get '/edit', to: 'devise/registrations#edit', :as => :edit
  end

  devise_for :users, controllers: { confirmations: 'confirmations', :passwords => "passwords" }

  get "home/index"
  root :to => "home#index"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Survey
    = stylesheet_link_tag    "application", :media => "all"
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    = javascript_include_tag "application"
    = csrf_meta_tags
    =favicon_link_tag('/assets/favicon.ico')
    = yield :head
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          = link_to "Home", home_index_path, class: "brand"
          %ul.nav.navbar-nav
            -if user_signed_in?
              %li= link_to "Results", diagnostics_path
            -else
              %li= link_to "Diagnostics", diagnostics_path
            -if user_signed_in? && current_user.admin?
              %li= link_to "Edit Diagnostics", diagnostics_edit_path
              %li= link_to "Users", users_path
          %ul.nav.navbar-nav.pull-right
            - if user_signed_in?
              %li= link_to current_user.full_name, edit_path
              %li= link_to "Log Out", logout_path
            - else
              %li= link_to "Log In", login_path
              %li= link_to "Register", register_path
    -if flash
      .container
        - flash.each do |type, message|
          %div{class: "alert alert-block #{flash_class(type)} span12"}
            %button.close{"data-dismiss" => "alert"} x
            %h4= flash_header message
            %div= message
    -if !(controller_name == "home" || (controller_name == "diagnostics" && controller.action_name == "admin") || (controller_name == "registrations" && controller.action_name == "new"))
      .container
        = yield
    - else
      = yield